
package com.example.quadratum.data

import com.example.quadratum.R
import com.example.quadratum.model.Exercise

/**
 * An object to generate a static list of exercises
 */
object DataSource {

//TODO: adapter to convert some data into a list


    val exercises: List<Exercise> = listOf(
        Exercise(
            R.drawable.ic_overheadpress,
            "Dumbbell Shoulder Press",
            "3",
            "To perform an overhead dumbbell press, start by standing with your feet shoulder-width apart and holding a dumbbell in each hand at shoulder height. Press the weights upward until your arms are fully extended above your head, then slowly lower them back down to the starting position. Keep your core engaged and avoid arching your back during the movement to maintain proper form and avoid injury."
        ),
        Exercise(
            R.drawable.situp,
            "Sit-ups",
            "4",
            "Lie on your back with your knees bent and feet flat on the ground. Place your hands behind your head or cross them over your chest. Engage your core and lift your upper body off the ground, bringing your chest towards your knees. Keep your feet on the ground throughout the movement. Slowly lower your upper body back down to the starting position with control."
        ),
        Exercise(
            R.drawable.squat,
            "Squat",
            "2",
            "Stand with your feet shoulder-width apart and your toes pointing slightly outward. Keep your chest up and your core engaged. Lower your hips back and down as if you are sitting in a chair, while keeping your weight on your heels. Keep your knees in line with your toes and avoid letting them collapse inward. Go as low as you comfortably can, then drive through your heels to stand back up to the starting position."
        ),
        Exercise(
            R.drawable.ic_treepose,
            "Tree-pose",
            "1",
            "Begin by standing with your feet together and your arms by your sides. Shift your weight onto your left foot, then lift your right foot and place the sole of your foot against the inner thigh of your left leg. Press your foot firmly into your thigh and bring your hands together in front of your chest in a prayer position. Balance on your left foot and hold the pose for several breaths, then release and repeat on the other side. It's important to keep your gaze forward and your core engaged to maintain balance and stability in the pose."
        ),
        Exercise(
            R.drawable.push_up,
            "Plank",
            "8",
            "Start in a push-up position with your hands directly under your shoulders and your body in a straight line from your head to your heels. Engage your core and glutes to maintain a straight spine and avoid sagging or arching your back. Hold the position for as long as you can while maintaining proper form, making sure to breathe deeply throughout the exercise."
        ),
        Exercise(
            R.drawable.upper_chest_training,
            "Incline Chest-press",
            "3",
            " Sit on an incline bench with your back flat against the bench and your feet firmly planted on the ground. Hold a dumbbell in each hand and raise them up to shoulder height, with your palms facing forward. Press the dumbbells upwards above your head until your arms are fully extended, then slowly lower them back down to shoulder height in a controlled manner. Keep your elbows in line with your shoulders throughout the movement and avoid locking your elbows at the top of the press. "
        ),
        Exercise(
            R.drawable.lunge,
            "Lunge",
            "1",
            "Start by standing with your feet hip-width apart. Take a big step forward with your right foot and lower your body until your right thigh is parallel to the ground, with your knee directly above your ankle. Your left knee should be hovering just above the ground. Push through your right heel to lift yourself back up to the starting position. Repeat on the other leg, alternating back and forth for the desired number of reps. Keep your upper body straight and avoid leaning forward during the movement."
        ),
        Exercise(
            R.drawable.ic_singledumbbell,
            "Kettlebell lift",
            "2",
            "Start by standing with your feet shoulder-width apart and a kettlebell on the ground in front of you. Hinge at the hips and grasp the kettlebell with both hands, keeping your back straight and your core engaged. Lift the kettlebell up off the ground and swing it back between your legs, then explosively swing it forward and up to chest height using the momentum generated by your hip hinge. Keep your arms straight but relaxed during the movement and avoid using your shoulders to lift the weight. Control the kettlebell as it swings back down between your legs. "
        ),
        Exercise(
            R.drawable.pullup,
            "Pull-Up",
            "5",
            "Start by hanging from a pull-up bar with your palms facing away from you and your hands shoulder-width apart. Engage your back and core muscles, then pull your body up towards the bar until your chin clears the bar. Keep your elbows close to your body and avoid swinging or using momentum to lift yourself up. Lower yourself back down to the starting position with control"
        )
    )
}

